version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    ports:
      - "4000:4000"
    volumes:
      - ./config_evaluator.yaml:/app/config_evaluator.yaml # Mount the local configuration file
    command: [ "--config", "/app/config_evaluator.yaml", "--port", "4000" ]
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/postgres"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env
    networks:
      - my_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - my_network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  ollama:
